### PR TITLE
Bring develop into master

### PR DESCRIPTION
**Pull request by malachaifrazier**
Merged develop into master and corrected all conflicts so active development may continue.

### CODE REVIEW

**Comment by scaffeinate** [comment]
+1 for the Pull Request @malachaifrazier. Let me test these and merge it 👍

**Comment by imanolGOMI** [comment]
+1!!

**Comment by imanolGOMI** [comment]
@scaffeinate can you test this? :P Thanks!

**Comment by scaffeinate** [comment]
@w0www Yes I did. But the develop branch isn't so stable. There are a number of things breaking with the new changes. So decided to fix those first before merging into master. I want the master to be stable release branch. And if I merge this one now it's gonna create conflicts when the new refactoring changes kick in. Check out this branch where I am fixing https://github.com/scaffeinate/socify/tree/feature/fix-dom

**Comment by imanolGOMI** [comment]
@scaffeinate   When you think that there will be a new stable version with all these changes? Thanks

**Comment by malachaifrazier** [comment]
Closed due to inactivity

**Pull request closed without merging**
