### PR TITLE
Update rails

### PR DESCRIPTION
**Pull request by briankung**
This updates Rails and fixes some compatibility problems along the way. I'm not sure if I should submit this to master or to develop?

### CODE REVIEW

**Comment by scaffeinate** [comment]
@briankung Let me check out the changes and merge it with master 👍

**Comment by briankung** [comment]
I picked ruby 2.3.1 for my own convenience, by the way, since it's what I'm using. Happy to make any suggested changes.

**Comment by scaffeinate** [comment]
@briankung Cool 😎

**Comment by scaffeinate** [comment]
@briankung Thank you for the PR. Successfully merged 👍

**Comment by briankung** [comment]
Thank _you_ for the excellent library. I'm probably going to use this as
the base for a side project, so you've made things immensely easier for me.
Cheers!

**Pull request merged**
